"""Real PostgreSQL integration for thermal confirmation storage, not Nostr crypto.

Reuse the disposable PostgreSQL 16 fixture. All credentials are generated by the
fixture; no household DSN, schema, messages, or service is accessed. The decoder
is explicitly a test double. SQLite, ActionEvent, ActionJournal and SQL are real.
"""
from datetime import datetime, timedelta, timezone
from hashlib import sha256
import json
from types import SimpleNamespace
from uuid import uuid4

import psycopg2
import pytest

import thermal_confirmation as confirmation
from thermal_model.journal import ActionJournal
from thermal_model.schema import ActionEvent
from test_thermal_journal import ephemeral_postgres  # noqa: F401; pytest fixture

UTC = timezone.utc
NOW = datetime(2026, 9, 22, 15, 0, tzinfo=UTC)


class AuthenticatedRumorFixture:
    """Intentionally bypasses crypto to test the real journal boundary only."""

    def __init__(self, rumor):
        self.rumor = rumor

    def decode(self, raw, recipient):
        return self.rumor


@pytest.fixture
def context(ephemeral_postgres, tmp_path):
    operator = sha256(uuid4().bytes).hexdigest()
    recipient = sha256(uuid4().bytes).hexdigest()
    draft = {
        "version": 1, "recipient": recipient, "operators": [operator],
        "prompts": [{
            "operator": operator,
            "issued_at": (NOW - timedelta(hours=1)).isoformat(),
            "expires_at": (NOW + timedelta(hours=1)).isoformat(),
            "actions": {"vent": "closed", "indoor_shade": "closed"},
        }],
    }
    policy = confirmation.Policy.load(confirmation.canonical(draft), assign_ids=True)
    spool = confirmation.Spool(tmp_path / "private")
    journal = ActionJournal(ephemeral_postgres.runtime_dsn)
    value = SimpleNamespace(policy=policy, spool=spool, journal=journal,
                            sink=confirmation.JournalSink(journal, ActionEvent))
    try:
        yield value
    finally:
        value.spool.close()


def rumor(context, content="yes", *, policy=None, at=NOW):
    policy = policy or context.policy
    prompt = policy.prompts[-1]
    result = {
        "pubkey": prompt.operator, "created_at": int(at.timestamp()), "kind": 14,
        "tags": [["p", policy.recipient], ["e", prompt.event_id]], "content": content,
    }
    result["id"] = confirmation.event_id(result)
    return result


def ingest(context, message=None, *, policy=None, now=NOW, raw=b"encrypted fixture"):
    return confirmation.ingest(
        raw, policy or context.policy, context.spool,
        AuthenticatedRumorFixture(message or rumor(context)), context.sink, now=now,
    )


def test_real_confirmation_batch_and_receipt_are_exact(context, ephemeral_postgres):
    receipt = ingest(context)
    expected = context.spool.get(receipt["rumor_id"])
    rows = context.journal.events_for_receipt(receipt["idempotency_key"])
    assert len(rows) == 2
    assert {row.action for row in rows} == {"vent", "indoor_shade"}
    assert all(row.source == "nostr_confirmed" and row.received_at == NOW for row in rows)
    assert {row.event_id for row in rows} == set(receipt["action_event_ids"])
    assert not context.journal.modes_for_receipt(receipt["idempotency_key"])
    with psycopg2.connect(ephemeral_postgres.runtime_dsn) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT received_at, payload_digest FROM thermal_intel.message_receipts "
                "WHERE idempotency_key=%s", (receipt["idempotency_key"],),
            )
            stored = cursor.fetchone()
    assert stored[0] == NOW
    assert stored[1].strip() == sha256(expected["rumor_json"].encode()).hexdigest()


def test_real_rewrapped_replay_after_restart_preserves_first_receipt(context, tmp_path):
    first = ingest(context)
    original = context.journal.events_for_receipt(first["idempotency_key"])
    context.spool.close()
    context.spool = confirmation.Spool(tmp_path / "private")
    # Expiry is not extended: an already accepted receipt is reverified verbatim.
    again = ingest(context, now=NOW + timedelta(days=3), raw=b"another encrypted wrapper")
    assert again == first
    assert context.journal.events_for_receipt(first["idempotency_key"]) == original
    assert context.spool.get(first["rumor_id"])["original_wrap"] == b"encrypted fixture"


def test_real_commit_then_readback_failure_retries_without_duplicate(context, monkeypatch):
    original = context.journal.events_for_receipt

    def fail_readback(_key):
        raise psycopg2.OperationalError("synthetic readback outage")

    monkeypatch.setattr(context.journal, "events_for_receipt", fail_readback)
    with pytest.raises(confirmation.Retryable):
        ingest(context)
    key = "nostr:" + rumor(context)["id"]
    assert len(original(key)) == 2  # A real transaction has committed.
    assert context.spool.get(rumor(context)["id"])["acknowledgement"] is None
    monkeypatch.setattr(context.journal, "events_for_receipt", original)
    receipt = ingest(context, now=NOW + timedelta(minutes=5))
    assert receipt["first_received_at"] == NOW.isoformat()
    assert len(original(key)) == 2


def test_real_correction_appends_foreign_keys_and_preserves_original(context):
    first = ingest(context)
    original = context.journal.events_for_receipt(first["idempotency_key"])
    draft = confirmation.policy_object(context.policy)
    correction = {**draft["prompts"][0], "correction_of": first["rumor_id"],
                  "actions": {"vent": "open", "indoor_shade": "closed"}}
    correction.pop("id")
    draft["prompts"].append(correction)
    policy = confirmation.Policy.load(confirmation.canonical(draft), assign_ids=True)
    message = rumor(context, "yes 08:45", policy=policy, at=NOW + timedelta(minutes=1))
    receipt = ingest(context, message, policy=policy, now=NOW + timedelta(minutes=1))
    stored = context.journal.events_for_receipt(receipt["idempotency_key"])
    assert context.journal.events_for_receipt(first["idempotency_key"]) == original
    assert {row.supersedes for row in stored} == {row.event_id for row in original}
    assert ingest(context, message, policy=policy, now=NOW + timedelta(minutes=2)) == receipt


def test_real_constraint_failure_rolls_back_entire_message_batch(context, ephemeral_postgres):
    message = rumor(context)
    _, records = confirmation.action_records(message, context.policy.prompts[0], NOW)
    # The final record references a nonexistent correction target. PostgreSQL
    # must roll back the earlier action AND receipt, not leave a partial batch.
    records[-1]["supersedes"] = uuid4().hex[:24]
    with pytest.raises(confirmation.Retryable):
        context.sink.store(records, confirmation.canonical(message))
    key = "nostr:" + message["id"]
    assert context.journal.events_for_receipt(key) == ()
    with psycopg2.connect(ephemeral_postgres.runtime_dsn) as connection:
        with connection.cursor() as cursor:
            cursor.execute("SELECT count(*) FROM thermal_intel.message_receipts "
                           "WHERE idempotency_key=%s", (key,))
            assert cursor.fetchone()[0] == 0


@pytest.mark.parametrize("reply", ["skip", "not yet"])
def test_real_nonconfirmation_never_creates_journal_receipt(context, ephemeral_postgres, reply):
    receipt = ingest(context, rumor(context, reply))
    assert receipt["status"] == "no_action_recorded"
    assert not context.journal.events_for_receipt(receipt["idempotency_key"])
    with psycopg2.connect(ephemeral_postgres.runtime_dsn) as connection:
        with connection.cursor() as cursor:
            cursor.execute("SELECT count(*) FROM thermal_intel.message_receipts "
                           "WHERE idempotency_key=%s", (receipt["idempotency_key"],))
            assert cursor.fetchone()[0] == 0


@pytest.mark.parametrize("operation", [
    "UPDATE thermal_intel.action_events SET note='forbidden' WHERE idempotency_key=%s",
    "DELETE FROM thermal_intel.action_events WHERE idempotency_key=%s",
])
def test_real_runtime_role_cannot_rewrite_collected_evidence(context, ephemeral_postgres, operation):
    receipt = ingest(context)
    original = context.journal.events_for_receipt(receipt["idempotency_key"])
    with pytest.raises(psycopg2.Error):
        with psycopg2.connect(ephemeral_postgres.runtime_dsn) as connection:
            with connection.cursor() as cursor:
                cursor.execute(operation, (receipt["idempotency_key"],))
    assert context.journal.events_for_receipt(receipt["idempotency_key"]) == original
